import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Nattakarn's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className="flex flex-col w-full ">
        <Navbar/>
        {children}
        <Footer/>
      </body>
      
    </html>
  );
}
